travis:
  secure:
    BINSTAR_TOKEN: q3mb0LU44v8astnyLLPeP+mWZNLa5C/LfsUiX7IN9dIxyhz91yIBmTSsq9DY4RiWmM4klMOWEocosKM6oFSkYOixkjM/gZhO32XXKdJnO9Ih8XAGfK7468ro0MUT+yGG+O1IUb+td8XzpI8wjyqIAVfL/vsxbxmnh1CjwjsKmcO8RUvlOgVPqnFmw4CfD3I3hwEjUxZXDrAssbRlKV5XczNhK1watGY2fZPPcrP53UkhSdsIFs1t5TJK+pClYiBpRhe9o79Ug/jsbFY5m6aoZmpPTy0DUj1nUc+YcDolTbq+Egh7YBOuAFpHCnFQbq0O/FbK2AKMpgFKQCqE2XSk8S5T6q5Km/+jfpyyNAvOxwziUf+yUo23qRk5gU0w5FXw50zt21A+yj/afZNOCQxmn9QiSyPGBAzf62P2Q+zo0kvMFWodjaXZ2Bz3mwS4ZBobZKPNpgUpdyfw7E/zRbWeuFFg4+xHgrGGv3E6fz28QzmK07XFp8iW2b6iSNqU6Nxrh0iGU31pRc7BTyuX+7eoOmcy0hAhqgun+u63L/E1XXFFywUdZSG3/ttXlZcgvsJ1SI2jKm7W4UzEwRSH64ntqXSg/1oMhSc0bkajFRp/pdeVaUUd2Qkvxe8WQtm8pAan+qg+2eJBcdZajqYqwmksjzwnfCEpz/z5EYs1XXgbOHI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
